### ISSUE TITLE
IMEI received via deviceIMEINumber isn't correct

### ISSUE THREAD

**Issue by ahamzatariq** [Hina-Hussain/DeviceInformationPlugin#4]
I'm hitting the api to fetch device IMEI but it's returning an invalid IMEI number.

**Comment by HRockT** [comment]
> I'm hitting the api to fetch device IMEI but it's returning an invalid IMEI number.

have you fix it ?

**Comment by narantsatsral** [comment]
This api returned wrong IMEI number. Could you fix it?

**Comment by WONDERJEWEL** [comment]
I have the same problem with  IMEI 
any news?

**Comment by thedevsbuddy** [comment]
I checked my device's IEMI number via *#06# it shows a different IMEI and when using this package to get IMEI it shows a completely different IMEI number. it doesn't include any of the 2 IMEI available in the device. 
Please fix it asap.

**Comment by Hina-Hussain** [comment]
> I'm hitting the api to fetch device IMEI but it's returning an invalid IMEI number.

Android has disabled the access of imei number due to security violation issues. This package now return UUID to differentiate the devices instead of real imei no.
Thanks for reaching

**Comment by Hina-Hussain** [comment]
> I'm hitting the api to fetch device IMEI but it's returning an invalid IMEI number.

Android has disabled the access of imei number due to security violation issues. This package now return UUID to differentiate the devices instead of real imei no.
Thanks for reaching.

**Comment by Hina-Hussain** [comment]
> > I'm hitting the api to fetch device IMEI but it's returning an invalid IMEI number.
> 
> have you fix it ?

Android has disabled the access of imei number due to security violation issues. This package now return UUID to differentiate the devices instead of real imei no.
Thanks for reaching

**Comment by ahzmie** [comment]
> 

Is the UUID the same after phone software updates & after Uninstall > install on same device? If yes, please tell us how is it generated? depending on what variables?
