### ISSUE TITLE
permission is not granded ( only in android) 

### ISSUE THREAD

**Issue by victorsdd01** [Hina-Hussain/DeviceInformationPlugin#5]
somebody know why happened this? I add the user permission in the manifest but don't work when I want get the Imei, he display this message.

**Comment by nadas00** [comment]
@victorsdd01 did you solved it?

**Comment by victorsdd01** [comment]
Hello yes, thank for comment... if you need the solution tell me ;)

**Comment by nadas00** [comment]
> Hello yes, thank for comment... if you need the solution tell me ;)

I need help. Could you please tell me solution?

**Comment by nadas00** [comment]
any update?

**Comment by victorsdd01** [comment]
sorry bro, yeah sure, that solution that I found was make a request permission... I do a phone (calls) permission and works good, but the "IMEI" isn't the real imei is the androidID.

**Comment by Hina-Hussain** [comment]
We could not get direct IMEI no as android restricts it so it's just an alternative approach to identify the device uniqueness. So in updated android phone instead of imei this plugin return unique UDID key for device uniqueness.
Thanks.
